FROM ruby:2.3.1

ENV LANG C.UTF-8

ENV ENTRYKIT_VERSION 0.4.0

ENV APP_ROOT /app

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    git \
    libcurl4-openssl-dev \
    libghc-yaml-dev \
    libqt5webkit5-dev \
    libxml2-dev \
    libxslt-dev \
    libyaml-dev \
    linux-headers-amd64 \
    mysql-client \
    nginx \
    nodejs \
    openssl \
    ruby-dev \
    ruby-json \
    sudo \
    tzdata \
    vim \
    zlib1g-dev && \
    apt-get clean -y && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

# Create adachin user
RUN useradd -m adachin 
RUN passwd -d adachin
RUN sed -ri 's/^wheel:x:10:/wheel:x:10:adachin/' /etc/group
RUN sed -ri 's/^# %wheel/adachin/' /etc/sudoers

RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

RUN mkdir -p $APP_ROOT

WORKDIR $APP_ROOT

RUN echo 'gem: --no-document' >> ~/.gemrc && \
    cp ~/.gemrc /etc/gemrc && \
    chmod uog+r /etc/gemrc && \
    bundle config --global build.nokogiri --use-system-libraries

ENV QMAKE=/usr/lib/qt5/bin/qmake

# nginx
RUN groupadd nginx
RUN useradd -g nginx nginx
ADD nginx.conf /etc/nginx/nginx.conf
ADD adachin.conf /etc/nginx/conf.d/adachin.conf

EXPOSE 3000

# Service to run
COPY ./service.sh /root/
RUN chmod 744 /root/service.sh

CMD ["/root/service.sh"]

